"use client";

import { useState, useEffect } from "react";
import { useParams } from "next/navigation";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Lightbulb,
  RefreshCw,
  Sparkles,
  TrendingUp,
  AlertTriangle,
  CheckCircle,
  Loader2,
  BarChart3,
  Target,
} from "lucide-react";
import { TamFunnelChart, MarketBreakdownChart } from "@/components/charts";

interface ProjectMetrics {
  tam?: number;
  sam?: number;
  som?: number;
  vendedMarket?: number;
  whiteSpace?: number;
  greenfield?: number;
  brownfield?: number;
  jumpballs?: number;
  penetrationRate?: number;
}

interface Insight {
  id: string;
  text: string;
  category: "opportunity" | "risk" | "finding";
  metric?: string;
}

export default function InsightsPage() {
  const params = useParams();
  const projectId = params.id as string;

  const [loading, setLoading] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [executiveSummary, setExecutiveSummary] = useState<string>("");
  const [insights, setInsights] = useState<Insight[]>([]);
  const [metrics, setMetrics] = useState<ProjectMetrics>({});
  const [confidence, setConfidence] = useState<{
    level: "high" | "medium" | "low";
    rationale: string;
  } | null>(null);
  const [risks, setRisks] = useState<string[]>([]);

  const formatCurrency = (value: number) => {
    if (value >= 1_000_000_000) {
      return `$${(value / 1_000_000_000).toFixed(2)}B`;
    } else if (value >= 1_000_000) {
      return `$${(value / 1_000_000).toFixed(1)}M`;
    }
    return `$${value.toLocaleString()}`;
  };

  const generateInsights = async () => {
    setGenerating(true);
    try {
      const response = await fetch(`/api/projects/${projectId}/insights`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
      });

      if (!response.ok) {
        throw new Error("Failed to generate insights");
      }

      const reader = response.body?.getReader();
      const decoder = new TextDecoder();
      let summary = "";

      while (reader) {
        const { done, value } = await reader.read();
        if (done) break;

        const chunk = decoder.decode(value);
        const lines = chunk.split("\n");

        for (const line of lines) {
          if (line.startsWith("data: ")) {
            try {
              const data = JSON.parse(line.slice(6));

              if (data.type === "summary") {
                summary += data.content;
                setExecutiveSummary(summary);
              } else if (data.type === "metrics") {
                setMetrics(data.metrics);
              } else if (data.type === "insights") {
                setInsights(data.insights);
              } else if (data.type === "confidence") {
                setConfidence(data.confidence);
              } else if (data.type === "risks") {
                setRisks(data.risks);
              }
            } catch {
              // Ignore parse errors
            }
          }
        }
      }
    } catch (error) {
      console.error("Error generating insights:", error);
    } finally {
      setGenerating(false);
    }
  };

  // Load existing insights on mount
  useEffect(() => {
    const loadInsights = async () => {
      setLoading(true);
      try {
        const response = await fetch(`/api/projects/${projectId}/insights`);
        if (response.ok) {
          const data = await response.json();
          if (data.executiveSummary) {
            setExecutiveSummary(data.executiveSummary);
            setMetrics(data.metrics || {});
            setInsights(data.insights || []);
            setConfidence(data.confidence);
            setRisks(data.risks || []);
          }
        }
      } catch (error) {
        console.error("Error loading insights:", error);
      } finally {
        setLoading(false);
      }
    };

    loadInsights();
  }, [projectId]);

  const hasMetrics = metrics.tam || metrics.vendedMarket || metrics.whiteSpace;

  return (
    <div className="container py-8">
      <div className="flex items-center justify-between mb-8">
        <div>
          <h2 className="text-2xl font-bold">AI Insights</h2>
          <p className="text-muted-foreground">
            Executive summary and key findings generated by Claude
          </p>
        </div>
        <Button onClick={generateInsights} disabled={generating}>
          {generating ? (
            <>
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              Generating...
            </>
          ) : (
            <>
              <RefreshCw className="mr-2 h-4 w-4" />
              {executiveSummary ? "Regenerate" : "Generate Insights"}
            </>
          )}
        </Button>
      </div>

      <div className="grid gap-6 lg:grid-cols-3">
        {/* Executive Summary */}
        <Card className="lg:col-span-2">
          <CardHeader>
            <CardTitle className="flex items-center">
              <Sparkles className="mr-2 h-5 w-5 text-primary" />
              Executive Summary
            </CardTitle>
          </CardHeader>
          <CardContent>
            {loading ? (
              <div className="flex items-center justify-center h-48">
                <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
              </div>
            ) : executiveSummary ? (
              <div className="prose prose-sm max-w-none">
                <p className="whitespace-pre-wrap text-sm leading-relaxed">
                  {executiveSummary}
                </p>
              </div>
            ) : (
              <div className="flex items-center justify-center h-48 text-muted-foreground">
                <div className="text-center">
                  <Lightbulb className="h-12 w-12 mx-auto mb-4 opacity-50" />
                  <p>Click &quot;Generate Insights&quot; to create an executive summary</p>
                  <p className="text-xs mt-2">
                    Make sure to complete at least one analysis module first
                  </p>
                </div>
              </div>
            )}
          </CardContent>
        </Card>

        {/* Key Metrics */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center">
              <BarChart3 className="mr-2 h-5 w-5" />
              Key Metrics
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="p-4 bg-primary/10 rounded-lg">
              <p className="text-sm text-muted-foreground">TAM</p>
              <p className="text-2xl font-bold text-primary">
                {metrics.tam ? formatCurrency(metrics.tam) : "--"}
              </p>
            </div>
            <div className="p-4 bg-blue-100 rounded-lg">
              <p className="text-sm text-muted-foreground">Vended Market</p>
              <p className="text-2xl font-bold text-blue-600">
                {metrics.vendedMarket ? formatCurrency(metrics.vendedMarket) : "--"}
              </p>
            </div>
            <div className="p-4 bg-green-100 rounded-lg">
              <p className="text-sm text-muted-foreground">White Space</p>
              <p className="text-2xl font-bold text-green-600">
                {metrics.whiteSpace ? formatCurrency(metrics.whiteSpace) : "--"}
              </p>
            </div>
            {metrics.penetrationRate && (
              <div className="p-4 bg-muted rounded-lg">
                <p className="text-sm text-muted-foreground">Penetration Rate</p>
                <p className="text-2xl font-bold">
                  {metrics.penetrationRate.toFixed(1)}%
                </p>
              </div>
            )}
          </CardContent>
        </Card>
      </div>

      {/* Charts Row */}
      {hasMetrics && (
        <div className="grid gap-6 lg:grid-cols-2 mt-6">
          {metrics.tam && (
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">TAM / SAM / SOM</CardTitle>
              </CardHeader>
              <CardContent>
                <TamFunnelChart
                  tam={metrics.tam}
                  sam={metrics.sam}
                  som={metrics.som}
                />
              </CardContent>
            </Card>
          )}
          {(metrics.greenfield || metrics.brownfield || metrics.jumpballs) && (
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">White Space Breakdown</CardTitle>
              </CardHeader>
              <CardContent>
                <MarketBreakdownChart
                  segments={[
                    { name: "Greenfield", value: metrics.greenfield || 0, color: "hsl(142, 71%, 45%)" },
                    { name: "Brownfield", value: metrics.brownfield || 0, color: "hsl(45, 93%, 47%)" },
                    { name: "Jumpballs", value: metrics.jumpballs || 0, color: "hsl(24, 95%, 53%)" },
                  ].filter(s => s.value > 0)}
                />
              </CardContent>
            </Card>
          )}
        </div>
      )}

      {/* Key Insights */}
      <Card className="mt-6">
        <CardHeader>
          <CardTitle className="flex items-center">
            <Target className="mr-2 h-5 w-5" />
            Key Insights
          </CardTitle>
          <CardDescription>
            Board-ready bullet points with supporting figures
          </CardDescription>
        </CardHeader>
        <CardContent>
          {insights.length > 0 ? (
            <div className="space-y-3">
              {insights.map((insight) => (
                <div
                  key={insight.id}
                  className={`flex items-start gap-3 p-3 rounded-lg ${
                    insight.category === "opportunity"
                      ? "bg-green-50 border border-green-200"
                      : insight.category === "risk"
                      ? "bg-red-50 border border-red-200"
                      : "bg-muted"
                  }`}
                >
                  {insight.category === "opportunity" ? (
                    <TrendingUp className="h-5 w-5 text-green-600 flex-shrink-0 mt-0.5" />
                  ) : insight.category === "risk" ? (
                    <AlertTriangle className="h-5 w-5 text-red-600 flex-shrink-0 mt-0.5" />
                  ) : (
                    <CheckCircle className="h-5 w-5 text-primary flex-shrink-0 mt-0.5" />
                  )}
                  <div>
                    <p className="text-sm">{insight.text}</p>
                    {insight.metric && (
                      <p className="text-xs text-muted-foreground mt-1">
                        {insight.metric}
                      </p>
                    )}
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <div className="flex items-center justify-center h-32 text-muted-foreground">
              <p>Generate insights to see key findings</p>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Confidence & Risks */}
      <div className="grid gap-6 lg:grid-cols-2 mt-6">
        {/* Confidence Assessment */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center">
              <CheckCircle className="mr-2 h-5 w-5" />
              Confidence Assessment
            </CardTitle>
          </CardHeader>
          <CardContent>
            {confidence ? (
              <div>
                <div
                  className={`inline-flex items-center px-3 py-1 rounded-full text-sm font-medium mb-3 ${
                    confidence.level === "high"
                      ? "bg-green-100 text-green-800"
                      : confidence.level === "medium"
                      ? "bg-yellow-100 text-yellow-800"
                      : "bg-red-100 text-red-800"
                  }`}
                >
                  {confidence.level.charAt(0).toUpperCase() + confidence.level.slice(1)} Confidence
                </div>
                <p className="text-sm text-muted-foreground">
                  {confidence.rationale}
                </p>
              </div>
            ) : (
              <div className="flex items-center justify-center h-24 text-muted-foreground">
                <p>Generate insights to see confidence assessment</p>
              </div>
            )}
          </CardContent>
        </Card>

        {/* Key Risks */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center">
              <AlertTriangle className="mr-2 h-5 w-5" />
              Key Risks & Sensitivities
            </CardTitle>
          </CardHeader>
          <CardContent>
            {risks.length > 0 ? (
              <ul className="space-y-2">
                {risks.map((risk, index) => (
                  <li key={index} className="flex items-start gap-2 text-sm">
                    <span className="text-red-500 mt-1">•</span>
                    {risk}
                  </li>
                ))}
              </ul>
            ) : (
              <div className="flex items-center justify-center h-24 text-muted-foreground">
                <p>Generate insights to see risks</p>
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
